// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq0Qm7iraDkuQnF9ybtGqNSCEnFenfJUI',
    appId: '1:962379547213:web:ff6fecdc6c8033992b5204',
    messagingSenderId: '962379547213',
    projectId: 'daytalia-c2fb9',
    authDomain: 'daytalia-c2fb9.firebaseapp.com',
    storageBucket: 'daytalia-c2fb9.firebasestorage.app',
    measurementId: 'G-TP5QY6YPH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk1REfrvkseJOpqFf1GyebGtcaFS7JSGc',
    appId: '1:962379547213:android:b61af052640decc42b5204',
    messagingSenderId: '962379547213',
    projectId: 'daytalia-c2fb9',
    storageBucket: 'daytalia-c2fb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhT_gJsYZwKGFji6-bGvM0cGIVEnMIdQs',
    appId: '1:962379547213:ios:b8dbf25560f33fbe2b5204',
    messagingSenderId: '962379547213',
    projectId: 'daytalia-c2fb9',
    storageBucket: 'daytalia-c2fb9.firebasestorage.app',
    iosBundleId: 'com.parrel.daytalia',
  );

}